describe('bal-form', () => {
  beforeEach(() => {
    cy.visit('/test/form-arialabelledby.html')
    cy.waitForDesignSystem()
  })

  it('should check if checkbox input has correct aria-labelledby and label correct for attribute', () => {
    cy.getByTestId('checkbox-basic')
      .find('bal-checkbox > input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('checkbox-basic').find('bal-checkbox > label').invoke('attr', 'for').should('eq', result)
      })
  })

  it('should check if radio input has correct aria-labelledby and label correct for attribute', () => {
    cy.getByTestId('radio-basic')
      .find('bal-radio-group')
      .find('bal-radio')
      .eq(0)
      .find('input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('radio-basic')
          .find('bal-radio-group')
          .find('bal-radio')
          .eq(0)
          .find('label')
          .invoke('attr', 'for')
          .should('eq', result)
      })

    cy.getByTestId('radio-basic')
      .find('bal-radio-group')
      .find('bal-radio')
      .eq(1)
      .find('input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('radio-basic')
          .find('bal-radio-group')
          .find('bal-radio')
          .eq(1)
          .find('label')
          .invoke('attr', 'for')
          .should('eq', result)
      })

    cy.getByTestId('radio-basic')
      .find('bal-radio-group')
      .find('bal-radio')
      .eq(2)
      .find('input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('radio-basic')
          .find('bal-radio-group')
          .find('bal-radio')
          .eq(2)
          .find('label')
          .invoke('attr', 'for')
          .should('eq', result)
      })
  })

  it('should check if checkbox input in a field has correct aria-labelledby and label correct for attribute', () => {
    cy.getByTestId('form-checkbox')
      .find('bal-checkbox > input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('form-checkbox')
          .find('bal-checkbox > label')
          .invoke('attr', 'for')
          .should('eq', result.split(' ')[0])
        cy.getByTestId('form-checkbox')
          .find('bal-field-label > bal-label > label')
          .invoke('attr', 'id')
          .should('eq', result.split(' ')[1])
      })
  })

  it('should check if radio input in a field has correct aria-labelledby and label correct for attribute', () => {
    cy.getByTestId('form-radio')
      .find('bal-radio')
      .eq(0)
      .find('input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('form-radio')
          .find('bal-radio')
          .eq(0)
          .find('label')
          .invoke('attr', 'for')
          .should('eq', result.split(' ')[0])
        cy.getByTestId('form-radio')
          .find('bal-field-label > bal-label > label')
          .invoke('attr', 'id')
          .should('eq', result.split(' ')[1])
      })

    cy.getByTestId('form-radio')
      .find('bal-radio')
      .eq(1)
      .find('input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('form-radio')
          .find('bal-radio')
          .eq(1)
          .find('label')
          .invoke('attr', 'for')
          .should('eq', result.split(' ')[0])
        cy.getByTestId('form-radio')
          .find('bal-field-label > bal-label > label')
          .invoke('attr', 'id')
          .should('eq', result.split(' ')[1])
      })

    cy.getByTestId('form-radio')
      .find('bal-radio')
      .eq(2)
      .find('input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('form-radio')
          .find('bal-radio')
          .eq(2)
          .find('label')
          .invoke('attr', 'for')
          .should('eq', result.split(' ')[0])
        cy.getByTestId('form-radio')
          .find('bal-field-label > bal-label > label')
          .invoke('attr', 'id')
          .should('eq', result.split(' ')[1])
      })
  })

  it('should check if checkbox button input has correct aria-labelledby and label correct for attribute', () => {
    cy.getByTestId('checkbox-button')
      .find('bal-checkbox > input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('checkbox-button')
          .find('bal-checkbox > label')
          .invoke('attr', 'for')
          .should('eq', result.split(' ')[0])
        cy.getByTestId('checkbox-button')
          .find('bal-content > bal-label > label')
          .invoke('attr', 'id')
          .should('eq', result.split(' ')[1])
      })
  })

  it('should check if radio button input has correct aria-labelledby and label correct for attribute', () => {
    cy.getByTestId('radio-button')
      .find('bal-radio > input')
      .invoke('attr', 'aria-labelledby')
      .then(result => {
        cy.getByTestId('radio-button')
          .find('bal-content')
          .find('bal-label > label')
          .invoke('attr', 'id')
          .should('eq', result.trim())
      })
  })
})
