describe('bal-radio', () => {
  beforeEach(() => cy.visit('/components/bal-radio/test/bal-radio.visual.html').waitForDesignSystem())
  it('basic component', () => {
    cy.platform('desktop')
    cy.getByTestId('radio-basic').testVisual('radio-basic-desktop')
    cy.getByTestId('radio-invalid').testVisual('radio-invalid-desktop')
    cy.getByTestId('radio-disabled').testVisual('radio-disabled-desktop')
    cy.getByTestId('radio-others').testVisual('radio-others-desktop')
    cy.getByTestId('radio-long-label').testVisual('radio-long-label-desktop')
    cy.getByTestId('button-basic').testVisual('button-basic-desktop')
    cy.getByTestId('button-invalid').testVisual('button-invalid-desktop')
    cy.getByTestId('button-disabled').testVisual('button-disabled-desktop')
    cy.getByTestId('button-long-label').testVisual('button-long-label-desktop')
    cy.getByTestId('group-vertical').testVisual('group-vertical-desktop')
    cy.getByTestId('group-vertical-on-mobile').testVisual('group-vertical-on-mobile-desktop')

    cy.platform('mobile')
    cy.getByTestId('group-vertical').testVisual('group-vertical-desktop')
    cy.getByTestId('group-vertical-on-mobile').testVisual('group-vertical-on-mobile-desktop')
  })
})
