describe('bal-checkbox', () => {
  beforeEach(() => cy.visit('/components/bal-checkbox/test/bal-checkbox.visual.html').waitForDesignSystem())

  it('basic component', () => {
    cy.platform('desktop')
    cy.getByTestId('checkbox-basic').testVisual('checkbox-basic-desktop')
    cy.getByTestId('checkbox-invalid').testVisual('checkbox-invalid-desktop')
    cy.getByTestId('checkbox-disabled').testVisual('checkbox-disabled-desktop')
    cy.getByTestId('checkbox-others').testVisual('checkbox-others-desktop')
    cy.getByTestId('checkbox-long-label').testVisual('checkbox-long-label-desktop')
    cy.getByTestId('switch-basic').testVisual('switch-basic-desktop')
    cy.getByTestId('switch-invalid').testVisual('switch-invalid-desktop')
    cy.getByTestId('switch-disabled').testVisual('switch-disabled-desktop')
    cy.getByTestId('switch-others').testVisual('switch-others-desktop')
    cy.getByTestId('switch-long-label').testVisual('switch-long-label-desktop')
    cy.getByTestId('group-vertical').testVisual('group-vertical-desktop')
    cy.getByTestId('group-vertical-on-mobile').testVisual('group-vertical-on-mobile-desktop')
    cy.getByTestId('button-basic').testVisual('button-basic-desktop')
    cy.getByTestId('button-invalid').testVisual('button-invalid-desktop')
    cy.getByTestId('button-disabled').testVisual('button-disabled-desktop')
    cy.getByTestId('button-long-label').testVisual('button-long-label-desktop')

    cy.platform('mobile')
    cy.getByTestId('group-vertical').testVisual('group-vertical-mobile')
    cy.getByTestId('group-vertical-on-mobile').testVisual('group-vertical-on-mobile-mobile')
  })
})
