describe('bal-button', () => {
  beforeEach(() => cy.visit('/components/bal-button/test/bal-button.visual.html').waitForDesignSystem())

  it('basic component', () => {
    cy.platform('desktop')
    cy.getByTestId('primary').compareSnapshot('button-primary-desktop')
    cy.getByTestId('colors').compareSnapshot('button-colors-desktop')
    cy.getByTestId('sizes').compareSnapshot('button-sizes-desktop')
    cy.getByTestId('inverted').compareSnapshot('button-inverted-desktop')
    cy.getByTestId('expanded').compareSnapshot('button-expanded-desktop')
    cy.getByTestId('flat').compareSnapshot('button-flat-desktop')
    cy.getByTestId('outlined').compareSnapshot('button-outlined-desktop')
    cy.getByTestId('rounded').compareSnapshot('button-rounded-desktop')
    cy.getByTestId('shadow').compareSnapshot('button-shadow-desktop')
    cy.getByTestId('icon-right').compareSnapshot('button-icon-right-desktop')
    cy.getByTestId('variants').compareSnapshot('button-variants-desktop')
    cy.getByTestId('states').compareSnapshot('button-states-desktop')
    cy.getByTestId('square').compareSnapshot('button-square-desktop')
    cy.getByTestId('group').compareSnapshot('button-group-desktop')
    cy.getByTestId('links').compareSnapshot('button-links-desktop')
    cy.getByTestId('inverted-links').compareSnapshot('button-inverted-links-desktop')

    cy.platform('tablet')
    cy.getByTestId('primary').compareSnapshot('button-primary-tablet')
    cy.getByTestId('colors').compareSnapshot('button-colors-tablet')
    cy.getByTestId('sizes').compareSnapshot('button-sizes-tablet')
    cy.getByTestId('inverted').compareSnapshot('button-inverted-tablet')
    cy.getByTestId('expanded').compareSnapshot('button-expanded-tablet')
    cy.getByTestId('flat').compareSnapshot('button-flat-tablet')
    cy.getByTestId('outlined').compareSnapshot('button-outlined-tablet')
    cy.getByTestId('rounded').compareSnapshot('button-rounded-tablet')
    cy.getByTestId('shadow').compareSnapshot('button-shadow-tablet')
    cy.getByTestId('icon-right').compareSnapshot('button-icon-right-tablet')
    cy.getByTestId('variants').compareSnapshot('button-variants-tablet')
    cy.getByTestId('states').compareSnapshot('button-states-tablet')
    cy.getByTestId('square').compareSnapshot('button-square-tablet')
    cy.getByTestId('group').compareSnapshot('button-group-tablet')
    cy.getByTestId('links').compareSnapshot('button-links-tablet')
    cy.getByTestId('inverted-links').compareSnapshot('button-inverted-links-tablet')

    cy.platform('mobile')
    cy.getByTestId('primary').compareSnapshot('button-primary-mobile')
    cy.getByTestId('colors').compareSnapshot('button-colors-mobile')
    cy.getByTestId('sizes').compareSnapshot('button-sizes-mobile')
    cy.getByTestId('inverted').compareSnapshot('button-inverted-mobile')
    cy.getByTestId('expanded').compareSnapshot('button-expanded-mobile')
    cy.getByTestId('flat').compareSnapshot('button-flat-mobile')
    cy.getByTestId('outlined').compareSnapshot('button-outlined-mobile')
    cy.getByTestId('rounded').compareSnapshot('button-rounded-mobile')
    cy.getByTestId('shadow').compareSnapshot('button-shadow-mobile')
    cy.getByTestId('icon-right').compareSnapshot('button-icon-right-mobile')
    cy.getByTestId('variants').compareSnapshot('button-variants-mobile')
    cy.getByTestId('states').compareSnapshot('button-states-mobile')
    cy.getByTestId('square').compareSnapshot('button-square-mobile')
    cy.getByTestId('group').compareSnapshot('button-group-mobile')
    cy.getByTestId('links').compareSnapshot('button-links-mobile')
    cy.getByTestId('inverted-links').compareSnapshot('button-inverted-links-mobile')
  })
})
