describe('bal-button', () => {
  before(() => cy.page('/components/bal-button/test/bal-button.visual.html'))

  it('basic component', () => {
    cy.platform('desktop')
    cy.getByTestId('primary').compareSnapshot('button-primary-desktop', 0.0)
    cy.getByTestId('colors').compareSnapshot('button-colors-desktop', 0.0)
    cy.getByTestId('sizes').compareSnapshot('button-sizes-desktop', 0.0)
    cy.getByTestId('inverted').compareSnapshot('button-inverted-desktop', 0.0)
    cy.getByTestId('expanded').compareSnapshot('button-expanded-desktop', 0.0)
    cy.getByTestId('flat').compareSnapshot('button-flat-desktop', 0.0)
    cy.getByTestId('outlined').compareSnapshot('button-outlined-desktop', 0.0)
    cy.getByTestId('rounded').compareSnapshot('button-rounded-desktop', 0.0)
    cy.getByTestId('shadow').compareSnapshot('button-shadow-desktop', 0.0)
    cy.getByTestId('icon-right').compareSnapshot('button-icon-right-desktop', 0.0)
    cy.getByTestId('variants').compareSnapshot('button-variants-desktop', 0.0)
    cy.getByTestId('states').compareSnapshot('button-states-desktop', 0.0)
    cy.getByTestId('square').compareSnapshot('button-square-desktop', 0.0)
    cy.getByTestId('group').compareSnapshot('button-group-desktop', 0.0)
    cy.getByTestId('links').compareSnapshot('button-links-desktop', 0.0)
    cy.getByTestId('inverted-links').compareSnapshot('button-inverted-links-desktop', 0.0)

    // cy.platform('tablet')
    // cy.getByTestId('primary').compareSnapshot('button-primary-tablet', 0.0)
    // cy.getByTestId('variants').compareSnapshot('button-variants-tablet', 0.0)
    // cy.getByTestId('states').compareSnapshot('button-states-tablet', 0.0)
    // cy.getByTestId('alert').compareSnapshot('button-alert-tablet', 0.0)
    // cy.getByTestId('square').compareSnapshot('button-square-tablet', 0.0)

    // cy.platform('mobile')
    // cy.getByTestId('primary').compareSnapshot('button-primary-deskmobiletop', 0.0)
    // cy.getByTestId('variants').compareSnapshot('button-variants-mobile', 0.0)
    // cy.getByTestId('states').compareSnapshot('button-states-mobile', 0.0)
    // cy.getByTestId('alert').compareSnapshot('button-alert-mobile', 0.0)
    // cy.getByTestId('square').compareSnapshot('button-square-mobile', 0.0)
  })
})
