describe('css-spacing.visual', () => {
  beforeEach(() => cy.visit('/test/css-spacing.visual.html').platform('desktop').waitForDesignSystem())

  it('basic', () => {
    cy.platform('desktop')
    cy.getByTestId('padding').compareSnapshot('css-spacing-padding-desktop', 0.0)
    cy.getByTestId('padding-top').compareSnapshot('css-spacing-padding-top-desktop', 0.0)
    cy.getByTestId('padding-bottom').compareSnapshot('css-spacing-padding-bottom-desktop', 0.0)
    cy.getByTestId('padding-left').compareSnapshot('css-spacing-padding-left-desktop', 0.0)
    cy.getByTestId('padding-right').compareSnapshot('css-spacing-padding-right-desktop', 0.0)
    cy.getByTestId('padding-x').compareSnapshot('css-spacing-padding-x-desktop', 0.0)
    cy.getByTestId('padding-y').compareSnapshot('css-spacing-padding-y-desktop', 0.0)

    cy.getByTestId('margin').compareSnapshot('css-spacing-margin-desktop', 0.0)
    cy.getByTestId('margin-top').compareSnapshot('css-spacing-margin-top-desktop', 0.0)
    cy.getByTestId('margin-bottom').compareSnapshot('css-spacing-margin-bottom-desktop', 0.0)
    cy.getByTestId('margin-left').compareSnapshot('css-spacing-margin-left-desktop', 0.0)
    cy.getByTestId('margin-right').compareSnapshot('css-spacing-margin-right-desktop', 0.0)
    cy.getByTestId('margin-x').compareSnapshot('css-spacing-margin-x-desktop', 0.0)
    cy.getByTestId('margin-y').compareSnapshot('css-spacing-margin-y-desktop', 0.0)

    cy.platform('tablet')
    cy.getByTestId('padding').compareSnapshot('css-spacing-padding-tablet', 0.0)
    cy.getByTestId('padding-top').compareSnapshot('css-spacing-padding-top-tablet', 0.0)
    cy.getByTestId('padding-bottom').compareSnapshot('css-spacing-padding-bottom-tablet', 0.0)
    cy.getByTestId('padding-left').compareSnapshot('css-spacing-padding-left-tablet', 0.0)
    cy.getByTestId('padding-right').compareSnapshot('css-spacing-padding-right-tablet', 0.0)
    cy.getByTestId('padding-x').compareSnapshot('css-spacing-padding-x-tablet', 0.0)
    cy.getByTestId('padding-y').compareSnapshot('css-spacing-padding-y-tablet', 0.0)

    cy.getByTestId('margin').compareSnapshot('css-spacing-margin-tablet', 0.0)
    cy.getByTestId('margin-top').compareSnapshot('css-spacing-margin-top-tablet', 0.0)
    cy.getByTestId('margin-bottom').compareSnapshot('css-spacing-margin-bottom-tablet', 0.0)
    cy.getByTestId('margin-left').compareSnapshot('css-spacing-margin-left-tablet', 0.0)
    cy.getByTestId('margin-right').compareSnapshot('css-spacing-margin-right-tablet', 0.0)
    cy.getByTestId('margin-x').compareSnapshot('css-spacing-margin-x-tablet', 0.0)
    cy.getByTestId('margin-y').compareSnapshot('css-spacing-margin-y-tablet', 0.0)

    cy.platform('mobile')
    cy.getByTestId('padding').compareSnapshot('css-spacing-padding-mobile', 0.0)
    cy.getByTestId('padding-top').compareSnapshot('css-spacing-padding-top-mobile', 0.0)
    cy.getByTestId('padding-bottom').compareSnapshot('css-spacing-padding-bottom-mobile', 0.0)
    cy.getByTestId('padding-left').compareSnapshot('css-spacing-padding-left-mobile', 0.0)
    cy.getByTestId('padding-right').compareSnapshot('css-spacing-padding-right-mobile', 0.0)
    cy.getByTestId('padding-x').compareSnapshot('css-spacing-padding-x-mobile', 0.0)
    cy.getByTestId('padding-y').compareSnapshot('css-spacing-padding-y-mobile', 0.0)

    cy.getByTestId('margin').compareSnapshot('css-spacing-margin-mobile', 0.0)
    cy.getByTestId('margin-top').compareSnapshot('css-spacing-margin-top-mobile', 0.0)
    cy.getByTestId('margin-bottom').compareSnapshot('css-spacing-margin-bottom-mobile', 0.0)
    cy.getByTestId('margin-left').compareSnapshot('css-spacing-margin-left-mobile', 0.0)
    cy.getByTestId('margin-right').compareSnapshot('css-spacing-margin-right-mobile', 0.0)
    cy.getByTestId('margin-x').compareSnapshot('css-spacing-margin-x-mobile', 0.0)
    cy.getByTestId('margin-y').compareSnapshot('css-spacing-margin-y-mobile', 0.0)
  })
})
