describe('css-grid.visual', () => {
  beforeEach(() => cy.visit('/test/css-grid.visual.html').platform('desktop').waitForDesignSystem())

  it('basic', () => {
    cy.platform('desktop')
    cy.getByTestId('basic').compareSnapshot('css-grid-basic-desktop', 0.0)
    cy.getByTestId('column-sizes').compareSnapshot('css-grid-column-sizes-desktop', 0.0)
    cy.getByTestId('column-offset').compareSnapshot('css-grid-column-offset-desktop', 0.0)
    cy.getByTestId('rows').compareSnapshot('css-grid-rows-desktop', 0.0)
    cy.getByTestId('nested').compareSnapshot('css-grid-nested-desktop', 0.0)
    cy.getByTestId('space').compareSnapshot('css-grid-space-desktop', 0.0)
    cy.getByTestId('breakpoint').compareSnapshot('css-grid-breakpoint-desktop', 0.0)
    cy.getByTestId('vertical-alignment').compareSnapshot('css-grid-vertical-alignment-desktop', 0.0)
    cy.getByTestId('horizontal-alignment').compareSnapshot('css-grid-horizontal-alignment-desktop', 0.0)
    cy.getByTestId('stratch').compareSnapshot('css-grid-stratch-desktop', 0.0)

    cy.platform('tablet')
    cy.getByTestId('basic').compareSnapshot('css-grid-basic-tablet', 0.0)
    cy.getByTestId('column-sizes').compareSnapshot('css-grid-column-sizes-tablet', 0.0)
    cy.getByTestId('column-offset').compareSnapshot('css-grid-column-offset-tablet', 0.0)
    cy.getByTestId('rows').compareSnapshot('css-grid-rows-tablet', 0.0)
    cy.getByTestId('nested').compareSnapshot('css-grid-nested-tablet', 0.0)
    cy.getByTestId('space').compareSnapshot('css-grid-space-tablet', 0.0)
    cy.getByTestId('breakpoint').compareSnapshot('css-grid-breakpoint-tablet', 0.0)
    cy.getByTestId('vertical-alignment').compareSnapshot('css-grid-vertical-alignment-tablet', 0.0)
    cy.getByTestId('horizontal-alignment').compareSnapshot('css-grid-horizontal-alignment-tablet', 0.0)
    cy.getByTestId('stratch').compareSnapshot('css-grid-stratch-tablet', 0.0)

    cy.platform('mobile')
    cy.getByTestId('basic').compareSnapshot('css-grid-basic-mobile', 0.0)
    cy.getByTestId('column-sizes').compareSnapshot('css-grid-column-sizes-mobile', 0.0)
    cy.getByTestId('column-offset').compareSnapshot('css-grid-column-offset-mobile', 0.0)
    cy.getByTestId('rows').compareSnapshot('css-grid-rows-mobile', 0.0)
    cy.getByTestId('nested').compareSnapshot('css-grid-nested-mobile', 0.0)
    cy.getByTestId('space').compareSnapshot('css-grid-space-mobile', 0.0)
    cy.getByTestId('breakpoint').compareSnapshot('css-grid-breakpoint-mobile', 0.0)
    cy.getByTestId('vertical-alignment').compareSnapshot('css-grid-vertical-alignment-mobile', 0.0)
    cy.getByTestId('horizontal-alignment').compareSnapshot('css-grid-horizontal-alignment-mobile', 0.0)
    cy.getByTestId('stratch').compareSnapshot('css-grid-stratch-mobile', 0.0)
  })
})
