import {
  BalCheckbox,
  BalCheckboxGroup,
  BalDate,
  BalDropdown,
  BalFileUpload,
  BalInput,
  BalInputDate,
  BalInputSlider,
  BalInputStepper,
  BalNumberInput,
  BalRadioGroup,
  BalSegment,
  BalSelect,
  BalTextarea,
  BalTimeInput,
} from './components'
import { BalNgErrorComponent } from './directives/error.component'
import {
  BalAccordion,
  BalAccordionDetails,
  BalAccordionSummary,
  BalAccordionTrigger,
  BalApp,
  BalBadge,
  BalButton,
  BalButtonGroup,
  BalCard,
  BalCardActions,
  BalCardButton,
  BalCardContent,
  BalCardSubtitle,
  BalCardTitle,
  BalCarousel,
  BalCarouselItem,
  BalCheck,
  BalClose,
  BalContent,
  BalData,
  BalDataItem,
  BalDataLabel,
  BalDataValue,
  BalDateCalendar,
  BalDateCalendarCell,
  BalDivider,
  BalField,
  BalFieldControl,
  BalFieldHint,
  BalFieldLabel,
  BalFieldMessage,
  BalFooter,
  BalForm,
  BalFormCol,
  BalFormGrid,
  BalHeading,
  BalHint,
  BalHintText,
  BalHintTitle,
  BalIcon,
  BalInputGroup,
  BalLabel,
  BalList,
  BalListItem,
  BalListItemAccordionBody,
  BalListItemAccordionHead,
  BalListItemContent,
  BalListItemIcon,
  BalListItemSubtitle,
  BalListItemTitle,
  BalLogo,
  BalModal,
  BalModalBody,
  BalModalHeader,
  BalNav,
  BalNavbar,
  BalNavbarBrand,
  BalNavbarMenu,
  BalNavbarMenuEnd,
  BalNavbarMenuStart,
  BalNavLink,
  BalNavLinkGrid,
  BalNavLinkGridCol,
  BalNavLinkGroup,
  BalNavMenuBar,
  BalNavMenuFlyout,
  BalNavMetaBar,
  BalNotices,
  BalNotification,
  BalOption,
  BalOptionList,
  BalPagination,
  BalPopover,
  BalPopoverContent,
  BalPopup,
  BalProgressBar,
  BalRadio,
  BalRadioIcon,
  BalSegmentItem,
  BalSelectOption,
  BalShape,
  BalSheet,
  BalSnackbar,
  BalSpinner,
  BalStack,
  BalStage,
  BalStageBackLink,
  BalStageBody,
  BalStageFoot,
  BalStageHead,
  BalStageImage,
  BalStepItem,
  BalSteps,
  BalSwitch,
  BalTabItem,
  BalTable,
  BalTabs,
  BalTag,
  BalTagGroup,
  BalText,
  BalToast,
  BalTooltip,
} from './generated/proxies'

export const BalAccordionBundle = [BalAccordion, BalAccordionDetails, BalAccordionSummary, BalAccordionTrigger] as const

export const BalButtonBundle = [BalButton, BalButtonGroup] as const

export const BalCardBundle = [
  BalCard,
  BalCardContent,
  BalCardTitle,
  BalCardActions,
  BalCardSubtitle,
  BalCardButton,
] as const

export const BalDataBundle = [BalData, BalDataItem, BalDataLabel, BalDataValue] as const

export const BalHintBundle = [BalHint, BalHintText, BalHintTitle] as const

export const BalCarouselBundle = [BalCarousel, BalCarouselItem] as const

export const BalListBundle = [
  BalList,
  BalListItem,
  BalListItemAccordionHead,
  BalListItemAccordionBody,
  BalListItemContent,
  BalListItemIcon,
  BalListItemTitle,
  BalListItemSubtitle,
] as const

export const BalNavbarBundle = [BalNavbar, BalNavbarBrand, BalNavbarMenu, BalNavbarMenuStart, BalNavbarMenuEnd] as const

export const BalStageBundle = [
  BalStage,
  BalStageBackLink,
  BalStageBody,
  BalStageFoot,
  BalStageHead,
  BalStageImage,
] as const

export const BalTagBundle = [BalTag, BalTagGroup] as const

export const BalTabsBundle = [BalTabs, BalTabItem] as const

export const BalStepsBundle = [BalSteps, BalStepItem] as const

export const BalModalBundle = [BalModal, BalModalBody, BalModalHeader] as const

export const BalSelectBundle = [BalSelectOption, BalSelect] as const

export const BalCheckboxBundle = [BalCheckbox, BalCheckboxGroup, BalCheck, BalSwitch] as const

export const BalRadioBundle = [BalRadio, BalRadioIcon, BalRadioGroup] as const

export const BalFormGridBundle = [BalFormGrid, BalFormCol] as const

export const BalFieldBundle = [
  BalField,
  BalFieldLabel,
  BalFieldControl,
  BalFieldMessage,
  BalFieldControl,
  BalFieldHint,
] as const

export const BalDropdownBundle = [BalDropdown, BalOptionList, BalOption] as const

export const BalSegmentBundle = [BalSegment, BalSegmentItem] as const

/* Component Sections */

export const BalFormBundle = [
  //
  // Form Layout
  BalForm,
  BalInputGroup,
  ...BalFieldBundle,
  ...BalButtonBundle,
  ...BalFormGridBundle,
  BalNgErrorComponent,
  //
  // Form Controls
  ...BalCheckboxBundle,
  BalDate,
  ...BalDropdownBundle,
  BalInputDate,
  BalInputStepper,
  BalInputSlider,
  BalInput,
  BalNumberInput,
  ...BalRadioBundle,
  ...BalSelectBundle,
  ...BalSegmentBundle,
  BalFileUpload,
  BalTextarea,
  BalTimeInput,
] as const

export const BalLayoutBundle = [BalStack, BalContent, BalLogo, BalShape, BalApp, BalDivider, BalFooter] as const

export const BalTypographyBundle = [BalHeading, BalText, BalLabel] as const

export const BalComponentBundle = [
  BalNgErrorComponent,
  BalAccordion,
  BalAccordionDetails,
  BalAccordionSummary,
  BalAccordionTrigger,
  BalApp,
  BalBadge,
  BalButton,
  BalButtonGroup,
  BalCard,
  BalCardActions,
  BalCardButton,
  BalCardContent,
  BalCardSubtitle,
  BalCardTitle,
  BalCarousel,
  BalCarouselItem,
  BalCheck,
  BalCheckbox,
  BalCheckboxGroup,
  BalClose,
  BalContent,
  BalData,
  BalDataItem,
  BalDataLabel,
  BalDataValue,
  BalDate,
  BalDateCalendar,
  BalDateCalendarCell,
  BalDivider,
  BalDropdown,
  BalField,
  BalFieldControl,
  BalFieldHint,
  BalFieldLabel,
  BalFieldMessage,
  BalFileUpload,
  BalFooter,
  BalForm,
  BalFormCol,
  BalFormGrid,
  BalHeading,
  BalHint,
  BalHintText,
  BalHintTitle,
  BalIcon,
  BalInput,
  BalInputDate,
  BalInputGroup,
  BalInputSlider,
  BalInputStepper,
  BalLabel,
  BalList,
  BalListItem,
  BalListItemAccordionBody,
  BalListItemAccordionHead,
  BalListItemContent,
  BalListItemIcon,
  BalListItemSubtitle,
  BalListItemTitle,
  BalLogo,
  BalModal,
  BalModalBody,
  BalModalHeader,
  BalNav,
  BalNavLink,
  BalNavLinkGrid,
  BalNavLinkGridCol,
  BalNavLinkGroup,
  BalNavMenuBar,
  BalNavMenuFlyout,
  BalNavMetaBar,
  BalNavbar,
  BalNavbarBrand,
  BalNavbarMenu,
  BalNavbarMenuEnd,
  BalNavbarMenuStart,
  BalNotices,
  BalNotification,
  BalNumberInput,
  BalOption,
  BalOptionList,
  BalPagination,
  BalPopover,
  BalPopoverContent,
  BalPopup,
  BalProgressBar,
  BalRadio,
  BalRadioGroup,
  BalRadioIcon,
  BalSegment,
  BalSegmentItem,
  BalSelect,
  BalSelectOption,
  BalShape,
  BalSheet,
  BalSnackbar,
  BalSpinner,
  BalStack,
  BalStage,
  BalStageBackLink,
  BalStageBody,
  BalStageFoot,
  BalStageHead,
  BalStageImage,
  BalStepItem,
  BalSteps,
  BalSwitch,
  BalTabItem,
  BalTable,
  BalTabs,
  BalTag,
  BalTagGroup,
  BalText,
  BalTextarea,
  BalTimeInput,
  BalToast,
  BalTooltip,
] as const
