/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@baloise/design-system-components';

import { defineCustomElements } from '@baloise/design-system-components/loader';

defineCustomElements();
export const BalAccordion = /*@__PURE__*/createReactComponent<JSX.BalAccordion, HTMLBalAccordionElement>('bal-accordion');
export const BalButton = /*@__PURE__*/createReactComponent<JSX.BalButton, HTMLBalButtonElement>('bal-button');
export const BalCard = /*@__PURE__*/createReactComponent<JSX.BalCard, HTMLBalCardElement>('bal-card');
export const BalCardActions = /*@__PURE__*/createReactComponent<JSX.BalCardActions, HTMLBalCardActionsElement>('bal-card-actions');
export const BalCardButton = /*@__PURE__*/createReactComponent<JSX.BalCardButton, HTMLBalCardButtonElement>('bal-card-button');
export const BalCardContent = /*@__PURE__*/createReactComponent<JSX.BalCardContent, HTMLBalCardContentElement>('bal-card-content');
export const BalCardHead = /*@__PURE__*/createReactComponent<JSX.BalCardHead, HTMLBalCardHeadElement>('bal-card-head');
export const BalCardHeading = /*@__PURE__*/createReactComponent<JSX.BalCardHeading, HTMLBalCardHeadingElement>('bal-card-heading');
export const BalCardSteps = /*@__PURE__*/createReactComponent<JSX.BalCardSteps, HTMLBalCardStepsElement>('bal-card-steps');
export const BalCardSubtitle = /*@__PURE__*/createReactComponent<JSX.BalCardSubtitle, HTMLBalCardSubtitleElement>('bal-card-subtitle');
export const BalCardTitle = /*@__PURE__*/createReactComponent<JSX.BalCardTitle, HTMLBalCardTitleElement>('bal-card-title');
export const BalCheckbox = /*@__PURE__*/createReactComponent<JSX.BalCheckbox, HTMLBalCheckboxElement>('bal-checkbox');
export const BalData = /*@__PURE__*/createReactComponent<JSX.BalData, HTMLBalDataElement>('bal-data');
export const BalDataItem = /*@__PURE__*/createReactComponent<JSX.BalDataItem, HTMLBalDataItemElement>('bal-data-item');
export const BalDataLabel = /*@__PURE__*/createReactComponent<JSX.BalDataLabel, HTMLBalDataLabelElement>('bal-data-label');
export const BalDataValue = /*@__PURE__*/createReactComponent<JSX.BalDataValue, HTMLBalDataValueElement>('bal-data-value');
export const BalDatepicker = /*@__PURE__*/createReactComponent<JSX.BalDatepicker, HTMLBalDatepickerElement>('bal-datepicker');
export const BalDropdown = /*@__PURE__*/createReactComponent<JSX.BalDropdown, HTMLBalDropdownElement>('bal-dropdown');
export const BalDropdownMenu = /*@__PURE__*/createReactComponent<JSX.BalDropdownMenu, HTMLBalDropdownMenuElement>('bal-dropdown-menu');
export const BalDropdownTrigger = /*@__PURE__*/createReactComponent<JSX.BalDropdownTrigger, HTMLBalDropdownTriggerElement>('bal-dropdown-trigger');
export const BalField = /*@__PURE__*/createReactComponent<JSX.BalField, HTMLBalFieldElement>('bal-field');
export const BalFieldControl = /*@__PURE__*/createReactComponent<JSX.BalFieldControl, HTMLBalFieldControlElement>('bal-field-control');
export const BalFieldHint = /*@__PURE__*/createReactComponent<JSX.BalFieldHint, HTMLBalFieldHintElement>('bal-field-hint');
export const BalFieldLabel = /*@__PURE__*/createReactComponent<JSX.BalFieldLabel, HTMLBalFieldLabelElement>('bal-field-label');
export const BalFieldMessage = /*@__PURE__*/createReactComponent<JSX.BalFieldMessage, HTMLBalFieldMessageElement>('bal-field-message');
export const BalFileUpload = /*@__PURE__*/createReactComponent<JSX.BalFileUpload, HTMLBalFileUploadElement>('bal-file-upload');
export const BalHeading = /*@__PURE__*/createReactComponent<JSX.BalHeading, HTMLBalHeadingElement>('bal-heading');
export const BalHint = /*@__PURE__*/createReactComponent<JSX.BalHint, HTMLBalHintElement>('bal-hint');
export const BalHintText = /*@__PURE__*/createReactComponent<JSX.BalHintText, HTMLBalHintTextElement>('bal-hint-text');
export const BalHintTitle = /*@__PURE__*/createReactComponent<JSX.BalHintTitle, HTMLBalHintTitleElement>('bal-hint-title');
export const BalIcon = /*@__PURE__*/createReactComponent<JSX.BalIcon, HTMLBalIconElement>('bal-icon');
export const BalInput = /*@__PURE__*/createReactComponent<JSX.BalInput, HTMLBalInputElement>('bal-input');
export const BalList = /*@__PURE__*/createReactComponent<JSX.BalList, HTMLBalListElement>('bal-list');
export const BalListItem = /*@__PURE__*/createReactComponent<JSX.BalListItem, HTMLBalListItemElement>('bal-list-item');
export const BalListItemContent = /*@__PURE__*/createReactComponent<JSX.BalListItemContent, HTMLBalListItemContentElement>('bal-list-item-content');
export const BalListItemIcon = /*@__PURE__*/createReactComponent<JSX.BalListItemIcon, HTMLBalListItemIconElement>('bal-list-item-icon');
export const BalListItemSubtitle = /*@__PURE__*/createReactComponent<JSX.BalListItemSubtitle, HTMLBalListItemSubtitleElement>('bal-list-item-subtitle');
export const BalListItemTitle = /*@__PURE__*/createReactComponent<JSX.BalListItemTitle, HTMLBalListItemTitleElement>('bal-list-item-title');
export const BalModal = /*@__PURE__*/createReactComponent<JSX.BalModal, HTMLBalModalElement>('bal-modal');
export const BalModalActions = /*@__PURE__*/createReactComponent<JSX.BalModalActions, HTMLBalModalActionsElement>('bal-modal-actions');
export const BalModalBody = /*@__PURE__*/createReactComponent<JSX.BalModalBody, HTMLBalModalBodyElement>('bal-modal-body');
export const BalModalFooter = /*@__PURE__*/createReactComponent<JSX.BalModalFooter, HTMLBalModalFooterElement>('bal-modal-footer');
export const BalModalHeader = /*@__PURE__*/createReactComponent<JSX.BalModalHeader, HTMLBalModalHeaderElement>('bal-modal-header');
export const BalNavbar = /*@__PURE__*/createReactComponent<JSX.BalNavbar, HTMLBalNavbarElement>('bal-navbar');
export const BalNavbarBrand = /*@__PURE__*/createReactComponent<JSX.BalNavbarBrand, HTMLBalNavbarBrandElement>('bal-navbar-brand');
export const BalNavbarMenu = /*@__PURE__*/createReactComponent<JSX.BalNavbarMenu, HTMLBalNavbarMenuElement>('bal-navbar-menu');
export const BalNavbarMenuEnd = /*@__PURE__*/createReactComponent<JSX.BalNavbarMenuEnd, HTMLBalNavbarMenuEndElement>('bal-navbar-menu-end');
export const BalNavbarMenuStart = /*@__PURE__*/createReactComponent<JSX.BalNavbarMenuStart, HTMLBalNavbarMenuStartElement>('bal-navbar-menu-start');
export const BalNotification = /*@__PURE__*/createReactComponent<JSX.BalNotification, HTMLBalNotificationElement>('bal-notification');
export const BalPagination = /*@__PURE__*/createReactComponent<JSX.BalPagination, HTMLBalPaginationElement>('bal-pagination');
export const BalRadio = /*@__PURE__*/createReactComponent<JSX.BalRadio, HTMLBalRadioElement>('bal-radio');
export const BalRadioGroup = /*@__PURE__*/createReactComponent<JSX.BalRadioGroup, HTMLBalRadioGroupElement>('bal-radio-group');
export const BalSelect = /*@__PURE__*/createReactComponent<JSX.BalSelect, HTMLBalSelectElement>('bal-select');
export const BalSelectOption = /*@__PURE__*/createReactComponent<JSX.BalSelectOption, HTMLBalSelectOptionElement>('bal-select-option');
export const BalSheet = /*@__PURE__*/createReactComponent<JSX.BalSheet, HTMLBalSheetElement>('bal-sheet');
export const BalSnackbar = /*@__PURE__*/createReactComponent<JSX.BalSnackbar, HTMLBalSnackbarElement>('bal-snackbar');
export const BalSpinner = /*@__PURE__*/createReactComponent<JSX.BalSpinner, HTMLBalSpinnerElement>('bal-spinner');
export const BalTabItem = /*@__PURE__*/createReactComponent<JSX.BalTabItem, HTMLBalTabItemElement>('bal-tab-item');
export const BalTable = /*@__PURE__*/createReactComponent<JSX.BalTable, HTMLBalTableElement>('bal-table');
export const BalTabs = /*@__PURE__*/createReactComponent<JSX.BalTabs, HTMLBalTabsElement>('bal-tabs');
export const BalTag = /*@__PURE__*/createReactComponent<JSX.BalTag, HTMLBalTagElement>('bal-tag');
export const BalText = /*@__PURE__*/createReactComponent<JSX.BalText, HTMLBalTextElement>('bal-text');
export const BalTextarea = /*@__PURE__*/createReactComponent<JSX.BalTextarea, HTMLBalTextareaElement>('bal-textarea');
export const BalTimeinput = /*@__PURE__*/createReactComponent<JSX.BalTimeinput, HTMLBalTimeinputElement>('bal-timeinput');
export const BalToast = /*@__PURE__*/createReactComponent<JSX.BalToast, HTMLBalToastElement>('bal-toast');
