/**
 * Ambient type declaration for `@baloise/ds-core/hydrate`, this package's own SSR output —
 * imported only by `*.ssr.play.ts` test files.
 *
 * `hydrate/` is generated by this same `stencil build` run (see `dist-hydrate-script` in
 * `stencil.config.ts`) and gitignored, so on a fresh checkout it doesn't exist yet when Stencil's
 * internal TypeScript program typechecks `src` — including these test files — which happens
 * *before* output targets run. Without this ambient declaration, that typecheck fails with
 * "Cannot find module '@baloise/ds-core/hydrate'". Node's real module resolution at test-run time
 * is unaffected — it resolves the actual built output via the workspace symlink, same as always.
 */
declare module '@baloise/ds-core/hydrate' {
  export function renderToString(
    html: string,
    options?: Record<string, unknown>,
  ): Promise<{
    html: string | null
    hydratedCount: number
    diagnostics: { level: string; messageText: string }[]
  }>
}
