name: 💥 Breaking Change Report
description: Request a breaking change an existing feature
title: ':boom: breaking(component): title'
labels: ['💥 breaking change']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please describe your request in one or two sentences.
    validations:
      required: true
  - type: textarea
    id: current-solution
    attributes:
      label: Current Solution
      description: Please describe the current state and the problem with it and provide a code example like below.
      value: |
        Description...

        ```html
        <bal-component right></bal-component>
        ```
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What is the proposed solution? Please describe the solution and the advantages of it and provide a code example like below.
      value: |
        Description...

        ```html
        <bal-component position="left"></bal-component>
        <bal-component position="center"></bal-component>
        <bal-component position="right"></bal-component>
        ```
    validations:
      required: true
  - type: textarea
    id: next-steps
    attributes:
      label: Next Steps
      description: Present breaking change in the Baloise web community
      value: |
        - **Benefit** Show benefits of the change
          - list benefits here
        - **Effort** Discuss the impact of current running applications
          - describe the effort here
        - **Development** Discuss process of development
          - describe how the implementation will be done
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please include any additional information that may be relevant to your issue. Logs, related issues, Stack Overflow links, forum links or even a suggestions on how to fix.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/baloise/design-system?tab=coc-ov-file)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
