name: 🔧 Chore Task
description: Create a chore task for maintenance or architectural changes.
title: ':wrench: chore(component): title'
labels: ['🔧 chore']
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please describe the chore task.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please include any additional information that may be relevant to your issue. Logs, related issues, Stack Overflow links, forum links or even a suggestions on how to fix.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/baloise/design-system?tab=coc-ov-file)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
