name: ⚡️ Improve performance
description: Create a issue to improve performance
title: ':zap: perf(component): title'
labels: ['✨ feature', '⚡️ performance']
body:
  - type: textarea
    id: summary
    attributes:
      label: Description of this issue
    validations:
      required: true
  - type: input
    id: reproduction-url
    attributes:
      label: Code Reproduction URL
      description: Provide a URL to reproduce the issue
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Create a Lighthouse test and provide the following metrics.

        Use this tools to analyse:
        - [Introduction to Lighthouse](https://developer.chrome.com/docs/lighthouse/overview)
        - [PageSpeed Insights](https://pagespeed.web.dev)
  - type: input
    id: Performance
    attributes:
      label: Performance
    validations:
      required: true
  - type: input
    id: LargestContentfulPaint
    attributes:
      label: Largest Contentful Paint
    validations:
      required: true
  - type: input
    id: SpeedIndex
    attributes:
      label: Speed Index
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please include any additional information that may be relevant to your issue. Logs, related issues, Stack Overflow links, forum links or even a suggestions on how to fix.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/baloise/design-system/blob/next/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
