name: 🧪 Test Task
description: Create a test task to improve the Design System
title: ':test_tube: test(component): title'
labels: ['🧪 test']
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please describe the use case of this test task.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Please describe the acceptance criteria of the test task.
      value: |
        - [ ] Criteria 1
        - [ ] Criteria 2
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please include any additional information that may be relevant to your issue. Logs, related issues, Stack Overflow links, forum links or even a suggestions on how to fix.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/baloise/design-system?tab=coc-ov-file)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
