/**
 * version
 * --------------------------------------
 * Reads version from package.json and saves it to the browsers
 * window
 */

const path = require('path')
const changeCase = require('change-case')
const log = require('./utils/log.js')
const file = require('./utils/file.js')

const DIST_PATH = path.join(__dirname, '..', 'packages/components/src/constants/version.constant.ts')

async function main(){
  log.title('version')

  const lerna = require('../lerna.json')
  const version = lerna.version

  const content = `// generated by .build/version.js
export const VERSION = '${version}'
`
  await file.save(DIST_PATH, content)
}

main()
