describe('bal-button', () => {
  beforeEach(() => cy.visit('/components/bal-button/test/bal-button.visual.html').waitForDesignSystem())

  it('basic component', () => {
    cy.platform('desktop')
    cy.getByTestId('primary').testVisual('button-primary-desktop')
    cy.getByTestId('colors').testVisual('button-colors-desktop')
    cy.getByTestId('colors-alternatives').testVisual('button-colors-alternatives-desktop')
    cy.getByTestId('sizes').testVisual('button-sizes-desktop')
    cy.getByTestId('inverted').testVisual('button-inverted-desktop')
    cy.getByTestId('expanded').testVisual('button-expanded-desktop')
    cy.getByTestId('flat').testVisual('button-flat-desktop')
    cy.getByTestId('outlined').testVisual('button-outlined-desktop')
    cy.getByTestId('rounded').testVisual('button-rounded-desktop')
    cy.getByTestId('shadow').testVisual('button-shadow-desktop')
    cy.getByTestId('icon-right').testVisual('button-icon-right-desktop')
    cy.getByTestId('variants').testVisual('button-variants-desktop')
    cy.getByTestId('states').testVisual('button-states-desktop')
    cy.getByTestId('square').testVisual('button-square-desktop')
    cy.getByTestId('group').testVisual('button-group-desktop')
    cy.getByTestId('links').testVisual('button-links-desktop')
    cy.getByTestId('inverted-links').testVisual('button-inverted-links-desktop')

    cy.platform('tablet')
    cy.getByTestId('primary').testVisual('button-primary-tablet')
    cy.getByTestId('colors').testVisual('button-colors-tablet')
    cy.getByTestId('colors-alternatives').testVisual('button-colors-alternatives-tablet')
    cy.getByTestId('sizes').testVisual('button-sizes-tablet')
    cy.getByTestId('inverted').testVisual('button-inverted-tablet')
    cy.getByTestId('expanded').testVisual('button-expanded-tablet')
    cy.getByTestId('flat').testVisual('button-flat-tablet')
    cy.getByTestId('outlined').testVisual('button-outlined-tablet')
    cy.getByTestId('rounded').testVisual('button-rounded-tablet')
    cy.getByTestId('shadow').testVisual('button-shadow-tablet')
    cy.getByTestId('icon-right').testVisual('button-icon-right-tablet')
    cy.getByTestId('variants').testVisual('button-variants-tablet')
    cy.getByTestId('states').testVisual('button-states-tablet')
    cy.getByTestId('square').testVisual('button-square-tablet')
    cy.getByTestId('group').testVisual('button-group-tablet')
    cy.getByTestId('links').testVisual('button-links-tablet')
    cy.getByTestId('inverted-links').testVisual('button-inverted-links-tablet')

    cy.platform('mobile')
    cy.getByTestId('primary').testVisual('button-primary-mobile')
    cy.getByTestId('colors').testVisual('button-colors-mobile')
    cy.getByTestId('colors-alternatives').testVisual('button-colors-alternatives-mobile')
    cy.getByTestId('sizes').testVisual('button-sizes-mobile')
    cy.getByTestId('inverted').testVisual('button-inverted-mobile')
    cy.getByTestId('expanded').testVisual('button-expanded-mobile')
    cy.getByTestId('flat').testVisual('button-flat-mobile')
    cy.getByTestId('outlined').testVisual('button-outlined-mobile')
    cy.getByTestId('rounded').testVisual('button-rounded-mobile')
    cy.getByTestId('shadow').testVisual('button-shadow-mobile')
    cy.getByTestId('icon-right').testVisual('button-icon-right-mobile')
    cy.getByTestId('variants').testVisual('button-variants-mobile')
    cy.getByTestId('states').testVisual('button-states-mobile')
    cy.getByTestId('square').testVisual('button-square-mobile')
    cy.getByTestId('group').testVisual('button-group-mobile')
    cy.getByTestId('links').testVisual('button-links-mobile')
    cy.getByTestId('inverted-links').testVisual('button-inverted-links-mobile')
  })
})
