describe('bal-field', () => {
  beforeEach(() => cy.visit('/components/bal-field/test/bal-field.visual.html').waitForDesignSystem())

  it('basic component', () => {
    cy.platform('desktop')
    cy.getByTestId('basic').compareSnapshot('field-basic-desktop')
    cy.getByTestId('disabled').compareSnapshot('field-disabled-desktop')
    cy.getByTestId('invalid').compareSnapshot('field-invalid-desktop')
    cy.getByTestId('readonly').compareSnapshot('field-readonly-desktop')
    cy.getByTestId('required').compareSnapshot('field-required-desktop')
    cy.getByTestId('valid').compareSnapshot('field-valid-desktop')
    cy.getByTestId('label-long').compareSnapshot('label-long-desktop')
    cy.getByTestId('horizontal-alignment').compareSnapshot('horizontal-alignment-desktop')
    cy.getByTestId('horizontal-alignment-with-hint').compareSnapshot('horizontal-alignment-with-hint-desktop')

    cy.platform('tablet')
    cy.getByTestId('basic').compareSnapshot('field-basic-tablet')
    cy.getByTestId('disabled').compareSnapshot('field-disabled-tablet')
    cy.getByTestId('invalid').compareSnapshot('field-invalid-tablet')
    cy.getByTestId('readonly').compareSnapshot('field-readonly-tablet')
    cy.getByTestId('required').compareSnapshot('field-required-tablet')
    cy.getByTestId('valid').compareSnapshot('field-valid-tablet')
    cy.getByTestId('label-long').compareSnapshot('label-long-tablet')
    cy.getByTestId('horizontal-alignment').compareSnapshot('horizontal-alignment-tablet')
    cy.getByTestId('horizontal-alignment-with-hint').compareSnapshot('horizontal-alignment-with-hint-tablet')

    cy.platform('mobile')
    cy.getByTestId('basic').compareSnapshot('field-basic-mobile')
    cy.getByTestId('disabled').compareSnapshot('field-disabled-mobile')
    cy.getByTestId('invalid').compareSnapshot('field-invalid-mobile')
    cy.getByTestId('readonly').compareSnapshot('field-readonly-mobile')
    cy.getByTestId('required').compareSnapshot('field-required-mobile')
    cy.getByTestId('valid').compareSnapshot('field-valid-mobile')
    cy.getByTestId('label-long').compareSnapshot('label-long-mobile')
    cy.getByTestId('horizontal-alignment').compareSnapshot('horizontal-alignment-mobile')
    cy.getByTestId('horizontal-alignment-with-hint').compareSnapshot('horizontal-alignment-with-hint-mobile')
  })
})
