/**
 * Build script for docs — orchestrates assets, archives, contributors, and Storybook build
 *
 * Run with: node scripts/build-docs.mjs
 */
import archiver from 'archiver'
import { execSync } from 'node:child_process'
import { createWriteStream } from 'node:fs'
import { copy } from 'fs-extra'
import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const docsRoot = resolve(__dirname, '../docs')
const packagesRoot = resolve(__dirname, '../packages')

const args = process.argv.slice(2)
const serve = args.includes('--serve')

// ============================================================================
// 1. Copy resources and assets
// ============================================================================
async function copyResources() {
  console.log('📋 Copying resources...')

  async function copyToAsset(from, to) {
    try {
      await copy(from, join(docsRoot, 'src', 'assets', to), { overwrite: true })
    } catch (err) {
      console.warn(`⚠ Could not copy ${from}:`, err.message)
    }
  }

  async function copyToPublic(from, to) {
    try {
      await copy(from, join(docsRoot, 'public', to), { overwrite: true })
    } catch (err) {
      console.warn(`⚠ Could not copy ${from}:`, err.message)
    }
  }

  // Data files
  await copyToAsset(join(packagesRoot, 'assets/src/maps/svg.json'), 'data/maps.json')
  await copyToAsset(join(packagesRoot, 'assets/src/icons/svg.json'), 'data/icons.json')
  await copyToAsset(join(packagesRoot, 'assets/src/brand-icons/svg.json'), 'data/brand-icons.json')
  await copyToAsset(join(packagesRoot, 'css/dist/docs'), 'data/css')

  // Resources from core dist output (generated by Stencil compiler)
  await copyToAsset(join(packagesRoot, 'core/dist/components.json'), 'data/components.json')
  await copyToAsset(join(packagesRoot, 'core/dist/tags.json'), 'data/tags.json')

  // CSS files from packages/css build output
  await copyToPublic(join(packagesRoot, 'css/dist/css'), 'assets/css')

  // Web components build output
  await copyToPublic(join(packagesRoot, 'core/www/build'), 'build')

  // Assets
  await copyToAsset(join(packagesRoot, 'assets/src/maps/svg'), 'images/map-markers')
  await copyToPublic(join(packagesRoot, 'assets/src/icons/svg'), 'assets/images/icons')
  await copyToPublic(join(packagesRoot, 'assets/src/brand-icons/svg'), 'assets/images/brand-icons')
  await copyToPublic(join(packagesRoot, 'assets/src/fonts'), 'assets/fonts')

  console.log('✔ All resources copied')
}

// ============================================================================
// 2. Fetch and store contributors list
// ============================================================================
async function fetchContributors() {
  console.log('👥 Fetching contributors from GitHub...')
  const outPath = join(docsRoot, 'src/assets/data/contributors.json')

  let contributors = []
  try {
    const res = await fetch('https://api.github.com/repos/baloise/design-system/contributors')
    if (!res.ok) {
      throw new Error(`GitHub API returned ${res.status}`)
    }
    const json = await res.json()
    contributors = json
      .filter(c => c.type === 'User')
      .map(u => ({
        url: u.html_url,
        name: u.login,
        avatar: u.avatar_url,
      }))
    console.log(`✔ ${contributors.length} contributors fetched`)
  } catch (err) {
    console.warn('⚠ Could not fetch contributors from GitHub API:', err.message)
    console.warn('⚠ Using empty contributors list')
  }

  await writeFile(outPath, JSON.stringify(contributors, undefined, 2))
  console.log('✔ docs/src/assets/data/contributors.json written')
}

// ============================================================================
// 3. Create zip archives
// ============================================================================
async function createArchive(sourcePath, targetPath, fileName, fileScan = '**') {
  return new Promise((resolve, reject) => {
    const output = createWriteStream(join(targetPath, fileName))
    output.on('close', () => {
      console.log(`✔ ${fileName} (${output.bytesWritten} bytes)`)
      resolve()
    })
    output.on('error', err => {
      console.error(`✗ Failed to create ${fileName}:`, err.message)
      reject(err)
    })

    const archive = archiver('zip', { zlib: { level: 9 } })
    archive.on('error', err => {
      console.error(`✗ Archive error for ${fileName}:`, err.message)
      reject(err)
    })

    archive.pipe(output)
    archive.glob(fileScan, {
      cwd: sourcePath.replace(/\\/g, '/'),
      stat: true,
    })
    archive.finalize()
  })
}

async function createArchives() {
  console.log('📦 Creating zip archives...')

  const archiveTargets = [
    {
      name: 'fonts',
      source: join(packagesRoot, 'assets/src/fonts'),
      archiveName: 'fonts.zip',
    },
    {
      name: 'icons',
      source: join(packagesRoot, 'assets/src/icons/svg'),
      archiveName: 'icons.zip',
    },
    {
      name: 'brand-icons',
      source: join(packagesRoot, 'assets/src/brand-icons/svg'),
      archiveName: 'brand-icons.zip',
    },
    {
      name: 'map-markers',
      source: join(packagesRoot, 'assets/src/maps/svg'),
      archiveName: 'map-markers.zip',
    },
    {
      name: 'figma-tokens',
      source: join(packagesRoot, 'tokens/dist'),
      archiveName: 'figma-tokens.zip',
    },
  ]

  const downloadPath = join(docsRoot, 'public', 'assets', 'download')
  await mkdir(downloadPath, { recursive: true })

  for (const target of archiveTargets) {
    try {
      await createArchive(target.source, downloadPath, target.archiveName)
    } catch (err) {
      console.warn(`⚠ Skipping ${target.name} (${target.source} may not exist)`)
    }
  }

  console.log('✔ All archives created')
}

// ============================================================================
// 4. Build Storybook
// ============================================================================
function buildStorybook() {
  console.log('📚 Building Storybook...')
  try {
    execSync('npx storybook build -o ./dist --quiet --disable-telemetry', {
      cwd: docsRoot,
      stdio: 'inherit',
    })
    console.log('✔ Storybook build complete')
  } catch (err) {
    console.error('✗ Storybook build failed:', err.message)
    throw err
  }
}

// ============================================================================
// Main
// ============================================================================
async function main() {
  try {
    console.log('🏗 Building docs...\n')

    await copyResources()
    console.log()

    await fetchContributors()
    console.log()

    if (!serve) {
      await createArchives()
      console.log()

      buildStorybook()
    } else {
      console.log('⏭ Skipping archives and Storybook build (--serve mode)')
    }

    console.log('\n✨ Docs build complete!')
  } catch (err) {
    console.error('\n✗ Build failed:', err)
    process.exit(1)
  }
}

await main()
