/**
 * Build script for docs — orchestrates assets, archives, contributors, and Storybook build
 *
 * Run with: node scripts/build-docs.mjs
 */
import { ZipArchive } from 'archiver'
import { copy } from 'fs-extra'
import { execSync } from 'node:child_process'
import { createWriteStream } from 'node:fs'
import { mkdir, open } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const docsRoot = resolve(__dirname, '../docs')
const packagesRoot = resolve(__dirname, '../packages')

const args = process.argv.slice(2)
const serve = args.includes('--serve')

console.log(`
\x1b[35m┃\x1b[0m
\x1b[35m┃\x1b[0m  \x1b[1;37m🧩 Helvetia Design System\x1b[0m
\x1b[35m┃\x1b[0m  \x1b[90m📦 Building Docs Package\x1b[0m
\x1b[35m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m
`)

// ============================================================================
// 0. Index MDX files and create story path mapping
// ============================================================================
async function indexMdxFiles() {
  console.log('🔍 Indexing MDX files for story mapping...')
  const glob = (await import('fast-glob')).default

  try {
    const mdxFiles = await glob(['**/*.mdx'], {
      cwd: join(docsRoot, 'src'),
      ignore: ['node_modules/**', '.storybook/**'],
    })

    const storyPathMap = {}

    for (const filePath of mdxFiles) {
      // Convert file path to story ID, stripping leading numbers for sorting prefixes
      // 01-getting-started.mdx -> getting-started
      // foundation/02-colors.mdx -> foundation-colors
      // changelog.mdx -> changelog
      const storyId = filePath
        .replace(/\.mdx$/, '') // Remove .mdx extension
        .split('/') // Split by path separator
        .map(segment => segment.replace(/^\d+-/, '')) // Strip leading digits and dash from each segment
        .join('-') // Join segments with hyphen
        .replace(/([A-Z])/g, '-$1') // Add hyphen before capitals
        .toLowerCase() // Convert to lowercase
        .replace(/^-/, '') // Remove leading hyphen
        .replace(/-+/g, '-') // Collapse multiple hyphens

      storyPathMap[storyId] = filePath
    }

    // Write mapping file sorted alphabetically by story ID for consistent cross-platform output
    const sortedStoryPathMap = Object.fromEntries(
      Object.keys(storyPathMap)
        .sort()
        .map(k => [k, storyPathMap[k]]),
    )
    const mapPath = join(docsRoot, '.storybook', 'story-paths.json')
    await mkdir(dirname(mapPath), { recursive: true })
    const fd = await open(mapPath, 'w')
    try {
      await fd.writeFile(JSON.stringify(sortedStoryPathMap, null, 2))
    } finally {
      await fd.close()
    }

    console.log(`\x1b[32m✔\x1b[0m ${Object.keys(sortedStoryPathMap).length} MDX files indexed`)
  } catch (err) {
    console.error('✗ Failed to index MDX files:', err.message)
    throw err
  }
}

// ============================================================================
// 1. Copy resources and assets
// ============================================================================
async function copyResources() {
  console.log('📋 Copying resources...')

  async function copyToAsset(from, to) {
    try {
      await copy(from, join(docsRoot, 'src', 'assets', to), { overwrite: true })
    } catch (err) {
      console.warn(`⚠ Could not copy ${from}:`, err.message)
    }
  }

  async function copyToPublic(from, to) {
    try {
      await copy(from, join(docsRoot, 'public', to), { overwrite: true })
    } catch (err) {
      console.warn(`⚠ Could not copy ${from}:`, err.message)
    }
  }

  // Data files
  await copyToAsset(join(packagesRoot, 'assets/src/maps/svg.json'), 'data/maps.json')
  await copyToAsset(join(packagesRoot, 'assets/src/icons/svg.json'), 'data/icons.json')
  await copyToAsset(join(packagesRoot, 'assets/src/brand-icons/svg.json'), 'data/brand-icons.json')
  await copyToAsset(join(packagesRoot, 'css/dist/docs'), 'data/css')

  // CSS files from packages/css build output
  await copyToPublic(join(packagesRoot, 'css/dist/css/design-system.css'), 'assets/css/design-system.css')

  // Web components build output
  await copyToAsset(join(packagesRoot, 'core/docs/components.json'), 'data/components.json')

  // Resources from core dist output (generated by Stencil compiler)
  await copyToAsset(join(packagesRoot, 'core/docs/tags.json'), 'data/tags.json')
  await copyToPublic(join(packagesRoot, 'core/www/build'), 'build')

  // Assets
  await copyToAsset(join(packagesRoot, 'assets/src/maps/svg'), 'images/map-markers')
  await copyToPublic(join(packagesRoot, 'assets/src/icons/svg'), 'assets/images/icons')
  await copyToPublic(join(packagesRoot, 'assets/src/brand-icons/svg'), 'assets/images/brand-icons')
  await copyToPublic(join(packagesRoot, 'assets/src/fonts'), 'assets/fonts')

  console.log('\x1b[32m✔\x1b[0m All resources copied')
}

// ============================================================================
// 2. Fetch and store contributors list
// ============================================================================
async function fetchContributors() {
  const outPath = join(docsRoot, 'src/assets/data/contributors.json')

  // Skip in CI or serve mode — contributors.json is already in git
  if (process.env.CI || serve) {
    console.log('📦 Skipping contributors fetch (CI or serve mode)')
    return
  }

  try {
    // Fetch fresh data from GitHub
    console.log('👥 Fetching contributors from GitHub...')
    const res = await fetch('https://api.github.com/repos/baloise/design-system/contributors')
    if (!res.ok) {
      throw new Error(`GitHub API returned ${res.status}`)
    }

    const contentType = res.headers.get('content-type')
    if (!contentType?.includes('application/json')) {
      throw new Error(`Invalid content-type: ${contentType}`)
    }

    const json = await res.json()

    if (!Array.isArray(json)) {
      throw new Error('GitHub API response is not an array')
    }

    // Validate and sanitize contributors
    const contributors = json
      .filter(c => {
        return (
          typeof c === 'object' &&
          c !== null &&
          c.type === 'User' &&
          typeof c.html_url === 'string' &&
          typeof c.login === 'string' &&
          typeof c.avatar_url === 'string'
        )
      })
      .map(u => {
        try {
          new URL(u.html_url)
          new URL(u.avatar_url)
        } catch (e) {
          console.warn(`⚠ Skipping contributor with invalid URL: ${u.login}`)
          return null
        }

        return {
          url: u.html_url,
          name: String(u.login).slice(0, 255),
          avatar: String(u.avatar_url).slice(0, 2048),
        }
      })
      .filter(c => c !== null)

    console.log(`\x1b[32m✔\x1b[0m ${contributors.length} contributors fetched`)

    // Write to file atomically
    try {
      const fd = await open(outPath, 'wx')
      try {
        await fd.writeFile(JSON.stringify(contributors, undefined, 2))
      } finally {
        await fd.close()
      }
    } catch (e) {
      if (e.code !== 'EEXIST') {
        throw e
      }
    }
  } catch (err) {
    console.warn('⚠ Could not fetch contributors from GitHub API:', err.message)
    console.warn('⚠ Using cached contributors list if available')
  }

  console.log('\x1b[32m✔\x1b[0m docs/src/assets/data/contributors.json ready')
}

// ============================================================================
// 3. Create zip archives
// ============================================================================
async function createArchive(sourcePath, targetPath, fileName, fileScan = '**') {
  return new Promise((resolve, reject) => {
    const output = createWriteStream(join(targetPath, fileName))
    output.on('close', () => {
      console.log(`\x1b[32m✔\x1b[0m ${fileName} (${output.bytesWritten} bytes)`)
      resolve()
    })
    output.on('error', err => {
      console.error(`✗ Failed to create ${fileName}:`, err.message)
      reject(err)
    })

    const archive = new ZipArchive({ zlib: { level: 9 } })
    archive.on('error', err => {
      console.error(`✗ Archive error for ${fileName}:`, err.message)
      reject(err)
    })

    archive.pipe(output)
    archive.glob(fileScan, {
      cwd: sourcePath.replace(/\\/g, '/'),
      stat: true,
    })
    archive.finalize()
  })
}

async function createArchives() {
  console.log('📦 Creating zip archives...')

  const archiveTargets = [
    {
      name: 'fonts',
      source: join(packagesRoot, 'assets/src/fonts'),
      archiveName: 'fonts.zip',
    },
    {
      name: 'icons',
      source: join(packagesRoot, 'assets/src/icons/svg'),
      archiveName: 'icons.zip',
    },
    {
      name: 'brand-icons',
      source: join(packagesRoot, 'assets/src/brand-icons/svg'),
      archiveName: 'brand-icons.zip',
    },
    {
      name: 'map-markers',
      source: join(packagesRoot, 'assets/src/maps/svg'),
      archiveName: 'map-markers.zip',
    },
    {
      name: 'figma-tokens',
      source: join(packagesRoot, 'tokens/dist'),
      archiveName: 'figma-tokens.zip',
    },
  ]

  const downloadPath = join(docsRoot, 'public', 'assets', 'download')
  await mkdir(downloadPath, { recursive: true })

  for (const target of archiveTargets) {
    try {
      await createArchive(target.source, downloadPath, target.archiveName)
    } catch (err) {
      console.warn(`⚠ Skipping ${target.name} (${target.source} may not exist)`)
    }
  }

  console.log('\x1b[32m✔\x1b[0m All archives created')
}

// ============================================================================
// 4. Build Storybook
// ============================================================================
function buildStorybook() {
  console.log('📚 Building Storybook...')
  try {
    execSync('pnpm exec storybook build -o ./dist --quiet --disable-telemetry', {
      cwd: docsRoot,
      stdio: 'inherit',
    })
    console.log('\x1b[32m✔\x1b[0m Storybook build complete')
  } catch (err) {
    console.error('✗ Storybook build failed:', err.message)
    throw err
  }
}

// ============================================================================
// Main
// ============================================================================
async function main() {
  try {
    console.log('🏗️ Building docs...\n')

    await indexMdxFiles()
    console.log()

    await copyResources()
    console.log()

    await fetchContributors()
    console.log()

    if (!serve) {
      await createArchives()
      console.log()

      buildStorybook()
    } else {
      console.log('⏭ Skipping archives and Storybook build (--serve mode)')
    }

    console.log('\n✨ Docs build complete!')
  } catch (err) {
    console.error('\n✗ Build failed:', err)
    process.exit(1)
  }
}

await main()
