/**
 * Build script for docs — orchestrates assets, archives, contributors, and Storybook build
 *
 * Run with: node scripts/build-docs.mjs
 */
import { ZipArchive } from 'archiver'
import { execSync } from 'node:child_process'
import { createWriteStream } from 'node:fs'
import { copy } from 'fs-extra'
import { mkdir, writeFile, stat, open } from 'node:fs/promises'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const docsRoot = resolve(__dirname, '../docs')
const packagesRoot = resolve(__dirname, '../packages')

const args = process.argv.slice(2)
const serve = args.includes('--serve')

console.log(`
\x1b[35m┃\x1b[0m
\x1b[35m┃\x1b[0m  \x1b[1;37m🧩 Helvetia Design System\x1b[0m
\x1b[35m┃\x1b[0m  \x1b[90m📦 Building Docs Package\x1b[0m
\x1b[35m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m
`)

// ============================================================================
// 1. Copy resources and assets
// ============================================================================
async function copyResources() {
  console.log('📋 Copying resources...')

  async function copyToAsset(from, to) {
    try {
      await copy(from, join(docsRoot, 'src', 'assets', to), { overwrite: true })
    } catch (err) {
      console.warn(`⚠ Could not copy ${from}:`, err.message)
    }
  }

  async function copyToPublic(from, to) {
    try {
      await copy(from, join(docsRoot, 'public', to), { overwrite: true })
    } catch (err) {
      console.warn(`⚠ Could not copy ${from}:`, err.message)
    }
  }

  // Data files
  await copyToAsset(join(packagesRoot, 'assets/src/maps/svg.json'), 'data/maps.json')
  await copyToAsset(join(packagesRoot, 'assets/src/icons/svg.json'), 'data/icons.json')
  await copyToAsset(join(packagesRoot, 'assets/src/brand-icons/svg.json'), 'data/brand-icons.json')
  await copyToAsset(join(packagesRoot, 'css/dist/docs'), 'data/css')

  // Resources from core dist output (generated by Stencil compiler)
  await copyToAsset(join(packagesRoot, 'core/docs/components.json'), 'data/components.json')
  await copyToAsset(join(packagesRoot, 'core/docs/tags.json'), 'data/tags.json')

  // CSS files from packages/css build output
  await copyToPublic(join(packagesRoot, 'css/dist/css/design-system.css'), 'assets/css/design-system.css')

  // Web components build output
  await copyToPublic(join(packagesRoot, 'core/www/build'), 'build')

  // Assets
  await copyToAsset(join(packagesRoot, 'assets/src/maps/svg'), 'images/map-markers')
  await copyToPublic(join(packagesRoot, 'assets/src/icons/svg'), 'assets/images/icons')
  await copyToPublic(join(packagesRoot, 'assets/src/brand-icons/svg'), 'assets/images/brand-icons')
  await copyToPublic(join(packagesRoot, 'assets/src/fonts'), 'assets/fonts')

  console.log('\x1b[32m✔\x1b[0m All resources copied')
}

// ============================================================================
// 2. Fetch and store contributors list
// ============================================================================
async function fetchContributors() {
  const outPath = join(docsRoot, 'src/assets/data/contributors.json')
  const ONE_DAY_MS = 24 * 60 * 60 * 1000

  try {
    // Check if cache exists and is fresh
    const cacheStats = await stat(outPath).catch(() => null)
    const now = Date.now()
    const isCacheFresh = cacheStats && now - cacheStats.mtimeMs < ONE_DAY_MS

    // In serve mode, always use cached data if it exists
    if (serve) {
      if (cacheStats) {
        console.log('📦 Using cached contributors (server mode)')
        return
      }
      console.log('⚠ No cache found, creating empty contributors list (server mode)')
      // Use atomic write to avoid race condition
      const fd = await open(outPath, 'w')
      try {
        await fd.writeFile(JSON.stringify([], undefined, 2))
      } finally {
        await fd.close()
      }
      return
    }

    // If cache is fresh, use it
    if (isCacheFresh) {
      console.log('📦 Using cached contributors (less than 24h old)')
      return
    }

    // Fetch fresh data from GitHub
    console.log('👥 Fetching contributors from GitHub...')
    const res = await fetch('https://api.github.com/repos/baloise/design-system/contributors')
    if (!res.ok) {
      throw new Error(`GitHub API returned ${res.status}`)
    }

    // Validate content-type is JSON
    const contentType = res.headers.get('content-type')
    if (!contentType?.includes('application/json')) {
      throw new Error(`Invalid content-type: ${contentType}`)
    }

    const json = await res.json()

    // Validate response is an array
    if (!Array.isArray(json)) {
      throw new Error('GitHub API response is not an array')
    }

    // Validate and sanitize each contributor
    const contributors = json
      .filter(c => {
        // Validate structure
        return (
          typeof c === 'object' &&
          c !== null &&
          c.type === 'User' &&
          typeof c.html_url === 'string' &&
          typeof c.login === 'string' &&
          typeof c.avatar_url === 'string'
        )
      })
      .map(u => {
        // Validate URLs are valid HTTP/HTTPS URLs
        try {
          new URL(u.html_url)
          new URL(u.avatar_url)
        } catch (e) {
          console.warn(`⚠ Skipping contributor with invalid URL: ${u.login}`)
          return null
        }

        // Sanitize strings to prevent injection
        return {
          url: u.html_url,
          name: String(u.login).slice(0, 255),
          avatar: String(u.avatar_url).slice(0, 2048),
        }
      })
      .filter(c => c !== null)

    console.log(`\x1b[32m✔\x1b[0m ${contributors.length} contributors fetched`)
    // Use atomic write to avoid race condition
    const fd = await open(outPath, 'w')
    try {
      await fd.writeFile(JSON.stringify(contributors, undefined, 2))
    } finally {
      await fd.close()
    }
  } catch (err) {
    console.warn('⚠ Could not fetch contributors from GitHub API:', err.message)
    console.warn('⚠ Using cached contributors list if available')
  }

  console.log('\x1b[32m✔\x1b[0m docs/src/assets/data/contributors.json ready')
}

// ============================================================================
// 3. Create zip archives
// ============================================================================
async function createArchive(sourcePath, targetPath, fileName, fileScan = '**') {
  return new Promise((resolve, reject) => {
    const output = createWriteStream(join(targetPath, fileName))
    output.on('close', () => {
      console.log(`\x1b[32m✔\x1b[0m ${fileName} (${output.bytesWritten} bytes)`)
      resolve()
    })
    output.on('error', err => {
      console.error(`✗ Failed to create ${fileName}:`, err.message)
      reject(err)
    })

    const archive = new ZipArchive({ zlib: { level: 9 } })
    archive.on('error', err => {
      console.error(`✗ Archive error for ${fileName}:`, err.message)
      reject(err)
    })

    archive.pipe(output)
    archive.glob(fileScan, {
      cwd: sourcePath.replace(/\\/g, '/'),
      stat: true,
    })
    archive.finalize()
  })
}

async function createArchives() {
  console.log('📦 Creating zip archives...')

  const archiveTargets = [
    {
      name: 'fonts',
      source: join(packagesRoot, 'assets/src/fonts'),
      archiveName: 'fonts.zip',
    },
    {
      name: 'icons',
      source: join(packagesRoot, 'assets/src/icons/svg'),
      archiveName: 'icons.zip',
    },
    {
      name: 'brand-icons',
      source: join(packagesRoot, 'assets/src/brand-icons/svg'),
      archiveName: 'brand-icons.zip',
    },
    {
      name: 'map-markers',
      source: join(packagesRoot, 'assets/src/maps/svg'),
      archiveName: 'map-markers.zip',
    },
    {
      name: 'figma-tokens',
      source: join(packagesRoot, 'tokens/dist'),
      archiveName: 'figma-tokens.zip',
    },
  ]

  const downloadPath = join(docsRoot, 'public', 'assets', 'download')
  await mkdir(downloadPath, { recursive: true })

  for (const target of archiveTargets) {
    try {
      await createArchive(target.source, downloadPath, target.archiveName)
    } catch (err) {
      console.warn(`⚠ Skipping ${target.name} (${target.source} may not exist)`)
    }
  }

  console.log('\x1b[32m✔\x1b[0m All archives created')
}

// ============================================================================
// 4. Build Storybook
// ============================================================================
function buildStorybook() {
  console.log('📚 Building Storybook...')
  try {
    execSync('npx storybook build -o ./dist --quiet --disable-telemetry', {
      cwd: docsRoot,
      stdio: 'inherit',
    })
    console.log('\x1b[32m✔\x1b[0m Storybook build complete')
  } catch (err) {
    console.error('✗ Storybook build failed:', err.message)
    throw err
  }
}

// ============================================================================
// Main
// ============================================================================
async function main() {
  try {
    console.log('🏗 Building docs...\n')

    await copyResources()
    console.log()

    await fetchContributors()
    console.log()

    if (!serve) {
      await createArchives()
      console.log()

      buildStorybook()
    } else {
      console.log('⏭ Skipping archives and Storybook build (--serve mode)')
    }

    console.log('\n✨ Docs build complete!')
  } catch (err) {
    console.error('\n✗ Build failed:', err)
    process.exit(1)
  }
}

await main()
