import {
  IconClock,
  IconClose,
  IconInfoCircle,
  IconPlus,
  IconMinus,
  IconEdit,
  IconTrash,
  IconNavGoLeft,
  IconNavGoRight,
  IconNavGoDown,
  IconNavGoUp,
  IconCheck,
  IconDate,
  IconDocument,
  IconUpload,
  IconMenuBars,
  IconFacebook,
  IconInstagram,
  IconLink,
  IconLinkedin,
  IconTwitter,
  IconX,
  IconXing,
  IconYoutube,
  IconWeb,
  IconCaretDown,
  IconCaretLeft,
  IconCaretRight,
  IconCaretUp,
  IconFile,
  IconPicture,
  IconVideo,
  IconAudio,
  IconDownload,
  IconAlert,
  IconBell,
  IconInformation,
} from '../constants/icons.constant'
import { defaultLoggerConfig } from '../log'
import type { BalConfigState } from './config.types'

export const defaultIcons = {
  IconClock,
  IconClose,
  IconInfoCircle,
  IconPlus,
  IconMinus,
  IconEdit,
  IconTrash,
  IconNavGoLeft,
  IconNavGoRight,
  IconNavGoDown,
  IconNavGoUp,
  IconCheck,
  IconDate,
  IconDocument,
  IconUpload,
  IconMenuBars,
  IconFacebook,
  IconInstagram,
  IconLink,
  IconLinkedin,
  IconTwitter,
  IconX,
  IconXing,
  IconYoutube,
  IconWeb,
  IconCaretDown,
  IconCaretLeft,
  IconCaretRight,
  IconCaretUp,
  IconFile,
  IconPicture,
  IconVideo,
  IconAudio,
  IconDownload,
  IconAlert,
  IconBell,
  IconInformation,
}

export const defaultConfig: BalConfigState = {
  brand: 'helvetia',
  region: 'CH',
  language: 'de',
  allowedLanguages: ['de', 'fr', 'it', 'en'],
  icons: defaultIcons,
  fallbackLanguage: 'de',
  logger: defaultLoggerConfig,
  animated: true,
  httpFormSubmit: true,
  _generateHydrateForCustomElementsOutput: false,
}

export const defaultLocale = `${defaultConfig.language}-${defaultConfig.region}`
