import {
  balIconAudio,
  balIconCaretDown,
  balIconCaretLeft,
  balIconCaretRight,
  balIconCaretUp,
  balIconCheck,
  balIconClock,
  balIconClose,
  balIconDate,
  balIconDocument,
  balIconDownload,
  balIconEdit,
  balIconFacebook,
  balIconFile,
  balIconInfoCircle,
  balIconInstagram,
  balIconLink,
  balIconLinkedin,
  balIconMenuBars,
  balIconMinus,
  balIconNavGoDown,
  balIconNavGoLeft,
  balIconNavGoRight,
  balIconNavGoUp,
  balIconPicture,
  balIconPlus,
  balIconTrash,
  balIconTwitter,
  balIconUpload,
  balIconVideo,
  balIconWeb,
  balIconX,
  balIconXing,
  balIconYoutube,
} from '../constants/icons.constant'
import { defaultLoggerConfig } from '../log'
import type { BalConfigState } from './config.types'

export const defaultIcons = {
  balIconClock,
  balIconClose,
  balIconInfoCircle,
  balIconPlus,
  balIconMinus,
  balIconEdit,
  balIconTrash,
  balIconNavGoLeft,
  balIconNavGoRight,
  balIconNavGoDown,
  balIconNavGoUp,
  balIconCheck,
  balIconDate,
  balIconDocument,
  balIconUpload,
  balIconMenuBars,
  balIconFacebook,
  balIconInstagram,
  balIconLink,
  balIconLinkedin,
  balIconTwitter,
  balIconX,
  balIconXing,
  balIconYoutube,
  balIconWeb,
  balIconCaretDown,
  balIconCaretLeft,
  balIconCaretRight,
  balIconCaretUp,
  balIconFile,
  balIconPicture,
  balIconVideo,
  balIconAudio,
  balIconDownload,
}

export const defaultConfig: BalConfigState = {
  region: 'CH',
  language: 'de',
  allowedLanguages: ['de', 'fr', 'it', 'en'],
  icons: defaultIcons,
  fallbackLanguage: 'de',
  logger: defaultLoggerConfig,
  animated: true,
  httpFormSubmit: true,
  _generateHydrateForCustomElementsOutput: false,
}

export const defaultLocale = `${defaultConfig.language}-${defaultConfig.region}`
