name: 📦️ Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  DS_PUBLISH: false

jobs:
  Release:
    name: 📦️ Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PRE_RELEASE_GITHUB_TOKEN }}
      - uses: ./.github/workflows/actions/setup

      - name: Clean install
        run: npm ci

      - name: Create Pre-Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: '📦️ Release'
          commit: 'prepare release'
          createGithubReleases: false
          publish: echo "Publish"
        env:
          GITHUB_TOKEN: ${{ secrets.PRE_RELEASE_GITHUB_TOKEN }}

      - name: Echo Changeset output
        shell: bash
        run: |
          echo "Changeset published - ${{ steps.changesets.outputs.published }}"
          echo "Changeset publishedPackages - ${{ steps.changesets.outputs.publishedPackages }}"
          echo "Changeset hasChangesets - ${{ steps.changesets.outputs.hasChangesets }}"
          echo "Changeset pullRequestNumber - ${{ steps.changesets.outputs.pullRequestNumber }}"
